name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile All C++ Files
      run: |
        mkdir -p build
        g++ -std=c++17 -o Datastructures/Trees/Tree_sum_max Datastructures/Trees/*.cpp
        echo "Compilation successful!"
